- name: Configure Kali VM
  hosts: kali_boxes
  vars_prompt:
    - name: user_password
      prompt: "Enter the new password for the cyberfox user"
      private: yes

  vars:
    ansible_become_password: "password"
    target_user: "cyberfox"
    

  roles:
    - common
    - remote_access
    - obsidian
    - typora
    - sliver
  
  post_tasks:
    - name: Change password for the cyberfox user
      ansible.builtin.user:
        name: cyberfox
        password: "{{ user_password | password_hash('sha512') }}"
      become: yes


    - name: Create Remmina connection profile for the new box
      delegate_to: localhost  
      ansible.builtin.copy:
        dest: "~/.local/share/remmina/{{ inventory_hostname }}.remmina"
        content: |
          [remmina]
          name={{ inventory_hostname }}
          server={{ ansible_host }}
          protocol=RDP
          username=cyberfox
          password=.
          resolution_mode=1
          color_depth=32
          ssh_tunnel_enabled=0
          cert_ignore=1
        mode: '0600'

    - name: Setup Obsidian Taskbar
      ansible.builtin.include_tasks: tasks/add_to_panel.yml
      vars:
        app:
          name: "Obsidian"
          exec: "/usr/bin/obsidian --no-sandbox"
          icon: "obsidian"
          id: 200

    - name: Setup Typora Taskbar
      ansible.builtin.include_tasks: tasks/add_to_panel.yml
      vars:
        app:
          name: "Typora"
          exec: "/usr/bin/typora"
          icon: "typora"
          id: 201

    - name: Refresh Xfce Panel (Once at the end)
      ansible.builtin.shell: "export $(dbus-launch); xfce4-panel -r"
      become_user: "{{ target_user }}"
      ignore_errors: yes