Colours
set -g default-terminal 'screen-256color'

# Set history buffer
set -g history-limit 10000

# Status Line
set -g status-fg green
set -g status-bg black

# Remap prefix from C-b to C-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix


# split panes using | and -
bind = split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Allow current direcotry rebind
# Useful when we want to rebase dirs 
bind _ attach-session -t . -c '#{pane_current_path}'

# Commands in the status bar
set -g status-right-length 50
# Get local ip:
set-option -ag status-right "#[fg=red,bright,bg=default]#(ifconfig eth0 | grep 'inet ' | cut -d: -f2 | awk '{print $2}')"

