- name: Add Obsidian launcher to panel 1 (ID 50) 
  xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-50
    value: launcher
    value_type: string
    state: present

- name: Link Obsidian .desktop file to launcher 50 
  xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-50/items
    value: "obsidian.desktop"
    value_type: string
    state: present