- name: Add typora launcher to panel 1 (ID 51) 
  xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-51
    value: launcher
    value_type: string
    state: present

- name: Link typora .desktop file to launcher 51
  xfconf:
    channel: xfce4-panel
    property: /plugins/plugin-51/items
    value: "typora.desktop"
    value_type: string
    state: present